sudo: false
language: python
python:
  - "3.5"
# command to install dependencies
install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/advisor_client
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/advisor_server
  - pip install -U pip
  - pip install ./advisor_client
  - pip install -r requirements.txt
  - pip install -r advisor_client/requirements.txt
  - pip install pytest
# command to run tests
script:
  - bash advisor_client/advisor_client/run_unittest.sh
  - bash advisor_server/run_unittest.sh