sudo: false
language: python
cache: pip
python:
  - '3.5'
install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/advisor_client
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/advisor_server
  - pip install -U pip
  - pip install ./advisor_client
  - pip install -r requirements.txt
  - pip install -r advisor_client/requirements.txt
  - pip install pytest coverage codecov
script:
  - bash advisor_server/run_unittest.sh
after_success:
  - codecov
before_deploy:
  - cd ./advisor_client
deploy:
  provider: pypi
  user: areeh
  server: https://testpypi.python.org/pypi
  password:
    secure: ipgOS7JCKTwnGD8Kw6du6x+E1WriYy9ssIs5dzGiTID6aa4kZ1ZrHSUr5x+UrreiYNO721K6MADu9Yc4g9G51cCb+1tL3P6pJm8nJcxr1LvCJYlAroCA2EGtIyXzZDfMb99j6c5nDjlLVagHNmH9VA2Cmdoj53PKNfx5DyQxswpd5GYatrtz9btwPhY+dPbSBJh3bavFVXwYPMPFgE+sNuSRYN1NJaB5GFcC1m7RmGWJd4CgtkMJlwk1Q12LCgtJXs8GlUyMZjNquJqsu403LujlmdOzfyOHNBR2Ycb0cSGqRzUkLNMmcSjBvxdYyccbhdtmOSdDoKWhIB437RQQZtJtM6vrDRc+0TrqQ+glgfj2nvROq4YleDan0Z0tqOCHD+iscOvwe0FKSQ9Uh1f6EDPyXwGFz0NYQRbRrK6tM2/n7lu+7rOpv4Ds+2a9FYlh+jH/77TtMofPkuYaD8j9P1kP2Wzin67SJe02+B4gmV2SISwxN1qnZqLyTH8PmZrRx/gchQ2P0NzxsqsWhGG/Qb8O17UKpsa7hyfTFdYvWk1CKzoshI/2OVO+Zy3L4iJ+eUU2oFLzFTiVThdM4c6tiCHYvXAiKIKH6M1RZtfD6BEMKDZVS9LQV2fWH2R84ajZ6yQCcVNSRQNCahjU0Yb+2CZ2y3MBs5X0+noJd7ltGKk=
  on:
    tags: true
